# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "294971e7bed957f8c7a7e813ca997c0f"
name = "Follow The Herd"
handle = "follow-the-herd"
application_url = "https://bookmarks-presently-sitemap-zu.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://bookmarks-presently-sitemap-zu.trycloudflare.com/auth/callback", "https://bookmarks-presently-sitemap-zu.trycloudflare.com/auth/shopify/callback", "https://bookmarks-presently-sitemap-zu.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
